// -*- mode: c++; -*-

#ifndef XPDF_CONFIG_HH
#define XPDF_CONFIG_HH

#include <_config.hh>

#define XPDF_PACKAGE           PACKAGE
#define XPDF_PACKAGE_BUGREPORT PACKAGE_BUGREPORT
#define XPDF_PACKAGE_NAME      PACKAGE_NAME
#define XPDF_PACKAGE_STRING    PACKAGE_STRING
#define XPDF_PACKAGE_TARNAME   PACKAGE_TARNAME
#define XPDF_PACKAGE_VERSION   PACKAGE_VERSION
#define XPDF_VERSION           VERSION

#undef PACKAGE
#undef PACKAGE_BUGREPORT
#undef PACKAGE_NAME
#undef PACKAGE_STRING
#undef PACKAGE_TARNAME
#undef PACKAGE_VERSION
#undef VERSION

#endif // XPDF_DETAIL_CONFIG_HH
